DROP DATABASE mars_rover_db;

CREATE DATABASE mars_rover_db;

DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS preference;

CREATE TABLE preference
(
    preference_id  int          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rover_type     varchar(255) NOT NULL,
    mars_sol       int          NOT NULL,
    camera_fhaz    boolean,
    camera_rhaz    boolean,
    camera_mast    boolean,
    camera_chemcam boolean,
    camera_mahli   boolean,
    camera_mardi   boolean,
    camera_navcam  boolean,
    camera_pancam  boolean,
    camera_minites boolean
);

CREATE TABLE customer
(
    customer_id   int          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login         varchar(255) NOT NULL UNIQUE,
    password      varchar      NOT NULL,
    role_name     varchar      NOT NULL DEFAULT 'ROLE_USER',
    date_created  date         NOT NULL,
    date_updated  date,
    preference_id int          REFERENCES preference (preference_id) ON DELETE SET NULL
);